### PR TITLE
CO-964 & CO-965

### PR DESCRIPTION
**Pull request by davidfaber**
This is NOT a final solution to the tickets CO-964 & CO-965, but it is a good start.

Look at the comments!

Things to consider:
- What if the the tax for shipping is calculated based on 'shipping' or 'billing' (Woo-Setting `woocommerce_tax_based_on`), could work, hasn't been tested
- What if the tax_class for Shipping is set to 'inherit'? (Woo-Setting `woocommerce_shipping_tax_class`).
- What if multiple tax-classes apply.

Still, I hope it helps fixing shipping-tax-issues.

### CODE REVIEW

**Comment by paprykasz** [comment]
Hey @davidfaber 

thanks for the feedback. Shipping tax is kind of complicated one because we don't have much info on the order side and we try to match it with tax rates that currently exists.

Referring to tickets, we don't see a reason for getting tax directly from WooCommerce there. When shipping is free (0) then tax can be any value at the end 19,7 because price value for it will be always 0. Could you maybe explain why we should change it in the way that you drafted?

**Comment by davidfaber** [comment]
Hi @paprykasz,

I did this for one of our clients. The problem is, that there are multiple ways of handling taxes in WooCommerce and the one to use are defined by law for the country you're selling from. In Austria the shipping is simply our standard-tax-rate of 20%.

Now in the case of my client, when he imports an order with free shipping to JTL, the tax-rate given for shipping is 0%, which is financially not correct, as shipping should have 20% but can be ignored for most cases as the shipping is 0 anyhow. Now our client started to use automatic exports of orders from JTL to their accountant's finance-tool (BMD). This tool is then stupid enough to split up the order, as it contains to different tax-rates and books it in 2 different invoice-groups, which creates a complete mess.

Now you could say, that this is actually the finance-tool's fault and you might be right, but you could trust me, that it's the easier way to make JTL import the tax-rates from WooCommerce as it's defined there.

David

**Comment by paprykasz** [comment]
Hey @davidfaber 

we have discussed again your issue and we decided to implement solution for this. Since there is no tax information on free shipping in WooCommerce we can use highest vat rate from the 'standard' items. For example when you have items with: 7% and 20% then 20% will be used in case shipping tax rate is 0. This will be kind of fallback after existing calculations are performed and shipping vat rate is still 0. Let me know if you have any thoughts on this.

Patryk

**Comment by davidfaber** [comment]
Hi @paprykasz,

This is awesome news for my client! Thanks so much!

David

**Comment by paprykasz** [comment]
Hi @davidfaber 

Changes are now in QA as soon as they are approved there will be new release with this feature.

All the best,
Patryk

**Comment by davidfaber** [comment]
That it awesome news! Thanks for handling this issue so quickly!

**Pull request closed without merging**
